parameters:
  ps_cache_dir: !php/const _PS_CACHE_DIR_

services:
  distributionapiclient.cache.filesystem.adapter:
    class: Symfony\Component\Cache\Adapter\Filesystem_Adapter
    arguments:
      - ''
      - !php/const Presta_Shop\Module\Distribution_Api_Client\Distribution_Api::CACHE_LIFETIME_SECONDS
      - '%ps_cache_dir%/distribution-api'

  distributionapiclient.cache.provider:
    class: Doctrine\Common\Cache\Psr6\Doctrine_Provider
    factory: [ Doctrine\Common\Cache\Psr6\Doctrine_Provider, wrap ]
    arguments:
      - '@distributionapiclient.cache.filesystem.adapter'

  distributionapiclient.middleware.cachedhttpclient:
    class: Presta_Shop\Module\Distribution_Api_Client\Middleware\Cached_Http_Client
    arguments:
      $cache: '@distributionapiclient.cache.provider'

  distributionapiclient.symfony.client:
    class: Presta_Shop\Circuit_Breaker\Client\Symfony_Http_Client
    arguments:
      $client: '@distributionapiclient.middleware.cachedhttpclient'

  distributionapiclient.circuit_breaker.factory:
    class: Presta_Shop\Circuit_Breaker\Advanced_Circuit_Breaker_Factory

  distributionapiclient.circuit_breaker.settings:
    class: Presta_Shop\Circuit_Breaker\Factory_Settings
    arguments:
      - !php/const Presta_Shop\Module\Distribution_Api_Client\Distribution_Api::ALLOWED_FAILURES
      - !php/const Presta_Shop\Module\Distribution_Api_Client\Distribution_Api::TIMEOUT_IN_SECONDS
      - !php/const Presta_Shop\Module\Distribution_Api_Client\Distribution_Api::THRESHOLD_SECONDS
    calls:
      - setStorage: [ '@prestashop.core.circuit_breaker.storage' ]
      - setClient: [ '@distributionapiclient.symfony.client' ]

  distributionapiclient.circuit_breaker:
    class: Presta_Shop\Circuit_Breaker\Contract\Circuit_Breaker_Interface
    factory: [ '@distributionapiclient.circuit_breaker.factory', 'create' ]
    arguments: [ '@distributionapiclient.circuit_breaker.settings' ]

  Presta_Shop\Module\Distribution_Api_Client\Shop_Data_Provider:
    class: Presta_Shop\Module\Distribution_Api_Client\Shop_Data_Provider

  distributionapiclient.distribution_api:
    class: Presta_Shop\Module\Distribution_Api_Client\Distribution_Api
    arguments:
      - '@distributionapiclient.circuit_breaker'
      - '@prestashop.module.factory.sourcehandler'
      - '@prestashop.adapter.data_provider.module'
      - '@Presta_Shop\Module\Distribution_Api_Client\Shop_Data_Provider'
      - "@=service('prestashop.core.foundation.version').getSemVersion()"
      - '%ps_cache_dir%/downloads'
      - '%kernel.project_dir%'
    public: true

  Presta_Shop\Module\Distribution_Api_Client\Controller\Admin\Top_Contributors_Controller:
    autowire: true
    autoconfigure: true
    public: true
    tags: ['controller.service_arguments']
